In [1]:
import numpy as np

## -- Array Creation Routines
https://numpy.org/doc/stable/reference/routines.array-creation.html

In [90]:
np.array([[1,2,3], [4,5,6], [7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.empty(shape=(5,3), dtype=str)
np.identity(n=5)
np.ones(shape=(5,3))
np.zeros(shape=(5,3))
np.full(shape=(5,3), fill_value=10)

# create a diagonal matrix, or get diagonal from matrix
# k = -1 or 1, one diagonal below or above main diagonal
np.diag([1,2,3])
np.diag([[1,2,3], [4,5,6], [7,8,9]], k=0)

### arange

In [92]:
np.arange(start=0.5, stop=20, step=1.5)

array([ 0.5,  2. ,  3.5,  5. ,  6.5,  8. ,  9.5, 11. , 12.5, 14. , 15.5,
       17. , 18.5])

### linspace / logspace

In [78]:
np.linspace(start=0, stop=10, num=20, endpoint=False)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [81]:
np.linspace(start=np.array([1,2,3]), stop=np.array([10,20,30]), num=5, axis=1)

array([[ 1.  ,  3.25,  5.5 ,  7.75, 10.  ],
       [ 2.  ,  6.5 , 11.  , 15.5 , 20.  ],
       [ 3.  ,  9.75, 16.5 , 23.25, 30.  ]])

In [86]:
# first and last values are base ** start, base ** stop
np.logspace(start=0, stop=2, num=10, base=10)

array([  1.        ,   1.66810054,   2.7825594 ,   4.64158883,
         7.74263683,  12.91549665,  21.5443469 ,  35.93813664,
        59.94842503, 100.        ])

## -- Array Manipulation Routines

In [ ]:
# initialize arrays
u = np.array([1,2,3]); v = np.array([4,5,6])                              # 1D arrays (3,)
A = np.array([[1,2,3], [4,5,6]]); B = np.array([[10,20,30], [40,50,60]])  # 2D arrays (2x3)

### stacks

In [38]:
# stack along NEW axis
np.stack(arrays=[u, v], axis=1)    # axis=0 -> (2,3), axis=1 -> (3,2)
np.stack(arrays=[A, B], axis=1)    # axis=0 or 1 -> (2,2,3)

# stack as rows
np.hstack([u,v])  # -> (6,)
np.hstack([A,B])  # -> (2,6)

# stack as columns
np.vstack([u,v])  # -> (2,3)
np.vstack([A,b])  # -> (4,3)

(2, 2, 3)

### tile

In [55]:
np.tile(A=u, reps=5)

array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [56]:
np.tile(A=A, reps=5)

array([[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6, 4, 5, 6, 4, 5, 6, 4, 5, 6]])

### repeat

In [61]:
np.repeat(a=u, repeats=5, axis=0)

array([1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3])

In [63]:
np.repeat(a=A, repeats=3, axis=0)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [4, 5, 6],
       [4, 5, 6],
       [4, 5, 6]])

In [64]:
np.repeat(a=A, repeats=3, axis=1)

array([[1, 1, 1, 2, 2, 2, 3, 3, 3],
       [4, 4, 4, 5, 5, 5, 6, 6, 6]])

## -- Sorting, Searching, and Counting

In [ ]:
M = np.array(np.linspace(0.5,20,20)).reshape(10,2)

In [ ]:
np.unique(M, return_counts=True)

In [192]:
# argmax, argmin, nanargmax, nanargmin
np.argmax(M, axis=0)

array([9, 9], dtype=int64)

In [200]:
# output: [5, 0] means row index 5 0th element satisfies condition
np.argwhere(M > 10)

array([[5, 0],
       [5, 1],
       [6, 0],
       [6, 1],
       [7, 0],
       [7, 1],
       [8, 0],
       [8, 1],
       [9, 0],
       [9, 1]], dtype=int64)

In [201]:
np.nonzero(M)

(array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9],
       dtype=int64),
 array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       dtype=int64))

In [202]:
# condition, value if true, value if false
np.where(M < 10, 0, M)

array([[ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [10.76315789, 11.78947368],
       [12.81578947, 13.84210526],
       [14.86842105, 15.89473684],
       [16.92105263, 17.94736842],
       [18.97368421, 20.        ]])

## -- Functional Programming

In [100]:
M = np.array(np.linspace(0.5,20,20)).reshape(10,2)

### apply_along_axis

In [111]:
np.apply_along_axis(func1d=np.mean, axis=1, arr=M)

array([ 1.01315789,  3.06578947,  5.11842105,  7.17105263,  9.22368421,
       11.27631579, 13.32894737, 15.38157895, 17.43421053, 19.48684211])

In [106]:
# axis=1 -> operate across rows for each column
# i.e. average first and last row for each columns
function = lambda x: (x[0] + x[-1])/2
np.apply_along_axis(func1d=function, axis=0, arr=M)

array([ 9.73684211, 10.76315789])

### piecewise

In [140]:
# Wherever condlist[i] is True, funclist[i](x) is used as the output value.
# add *args or **kwargs after
# subtract even numbers by n, add odd numbers by n
x = np.arange(0, 20)
np.piecewise(x=x, 
             condlist=[x % 2 == 0, x % 2 == 1], 
             funclist=[lambda x, n: x - n, lambda x, n: x + n],
             n=100)

array([-100,  101,  -98,  103,  -96,  105,  -94,  107,  -92,  109,  -90,
        111,  -88,  113,  -86,  115,  -84,  117,  -82,  119])

## -- Statistics

In [ ]:
M = np.array(np.linspace(0.5,20,20)).reshape(10,2)

In [ ]:
# add nan to ignore nan values e.g. np.nanmean()
# axis=0 -> along each row, axis=1 along each col
np.mean(M, axis=None)
np.median(M, axis=None)
np.std(M, axis=None)
np.var(M, axis=None)

In [119]:
np.average(a=np.array([1,2,3]), weights=[0.3,0.2,0.3])

1.9999999999999998

### percentile / nanpercentile

In [117]:
# q=0 -> min, q=100 -> max
np.percentile(np.linspace(0,200,65), q=np.arange(1,100,5))

array([  2.,  12.,  22.,  32.,  42.,  52.,  62.,  72.,  82.,  92., 102.,
       112., 122., 132., 142., 152., 162., 172., 182., 192.])

## -- Random

For probability distributions: https://numpy.org/doc/stable/reference/random/generated/numpy.random.beta.html

In [187]:
x = [1,2,3,4,5]
np.random.shuffle(x)
x

[3, 5, 1, 2, 4]

In [176]:
np.random.choice(a=[1,2,3,4,5], size=2, replace=True, p=[0.15, 0.15, 0.20, 0.35, 0.15])

array([1, 4])

## -- Mathematical Functions
https://numpy.org/doc/stable/reference/routines.math.html

In [ ]:
M = np.array(np.linspace(0.5,20,20)).reshape(10,2)

In [ ]:
np.floor(M)
np.ceil(M)
np.prod(M, axis=None)
np.sum(M, axis=None)
np.cumprod(M, axis=0) # cumulatively multiply downwards across rows for each column
np.cumsum(M, axis=0)

## -- Linear Algebra

In [ ]:
# element-wise addition/multiplication
u+10; u+v; u*v

# dot product for 1D array // cross product for >2D array
np.dot(u,v)

# matrix multiplication
np.matmul(M.T, M) # two inputs
np.linalg.multi_dot([A, B, C]) # multiple inputs

# compute inverse matrix
np.linalg.inv(M)

## -- Input / Output

In [ ]:
np.savetxt("filename.csv", export_data, delimiter=",")